name: Delete one resource using Pipeline
on:
  push:
    branches:
      - main 
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Echo script
        run: echo Starting Script
      - name: Login with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Deleting one of the deployed resources
        run: az group delete --ids '/subscriptions/acf80b05-4935-4573-a50b-c2dbb0c67e6a/resourceGroups/DeployResources/providers/Microsoft.Storage/storageAccounts/storage7ypzclpgodtua' --yes 
