name: Delete one resource using Pipeline
on:
  push:
    branches:
      - main 
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Echo script
        run: echo Starting Script
      - name: Login with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Deleting one of the deployed resources
        run: |
            az deployment group delete --resource-group DeployResources --name storage7ypzclpgodtua